sudo: required
services:
  - docker
before_install:
  - curl https://sdk.cloud.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - glcoud components update kubectl
  - glcoud auth activate-service-account --key-file service-account.json
  